[features]
seeds = false
skip-lint = false

[programs.localnet]
ainft = "14M8GDtWobqndjTrJ4sDZJ2CY74TXyGWGJzJoAE4TNYh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/kristoffer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha  -p ./tsconfig.json -t 1000000  tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
